#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    if [[ $OSTYPE == 'darwin'* ]]; then
        STOW_FOLDERS="bin,nvim,personal,zsh,tmux,i3"
    else
        STOW_FOLDERS="bin,nvim,personal,zsh,tmux"
    fi
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
