#!/usr/bin/env bash

alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
alias vim="$VIM"
alias python="python3"
alias yolo="git push origin master --force --no-verify"
